### ISSUE TITLE
Question on Design Plans

### ISSUE THREAD

**Issue by matu3ba** [1nwf/zcrun#1]
Which of the following properties are planned?
- 1. option for full cleanup/reset after process/container being run with/without errors (stateless)
- 2. all namespaces specified by clone (network, pid, mount, and uts given, missing are IPC and user)
- 3. sane ziggified clone3 interface and/or stack routines (upstream Zig still uses clone2)
- 4. ziggigied clone3 for race free signaling
- 5. build/run API for all the filepath things, which now search hardcoded system paths
- 6. scope of rtnetlink with address, link, route is quite abit unclear and rtnetlink/ has no rtnetlink.zig (I guess network filters are not protocol aware besides "what kind of sys connection is it", but this looks like awefully lot configuration options)
- 7. syscall or Kernel object access filtering (seccomp, seccomp-bpf, landlock)
- 8. checking most relevant Kernel configs (https://en.wikipedia.org/wiki/Kernel_same-page_merging being the most obvious one)

Use case 1 is for testing and quality, 2 for completeness, 3 for long-living supervision processes (and testing 1) and efficiency, 4 for sane process control instead of the racy posix mess, 5+6 for reusability, 7 the fancy dancy stuff, 8 nice to have.

Very novice to sandboxing code, but I believe "must create a child process to enter the new PID namespace" is wrong, see "man 3 unshare": "unshare()  allows  a  process  (or thread) to disassociate parts of its execution context that are currently being shared with other processes (or threads)." Afaiu, only `exec`* must be used to start a new execution context, which is also what the example code shows.

**Comment by 1nwf** [comment]
1 and 2 are planned. Can you elaborate more on 3 and 4. I'm not quite sure what you're trying address there.

For 5, I think it's currently unnecessary to have a separate build step since its minimal and coupled with
the run step. Although, feel free to propose what you think that should look like.

6. see [rtnetlink.zig](https://github.com/1nwf/zcrun/blob/main/src/rtnetlink/rtnetlink.zig).
7.  not initially planned although might be partially supported. 
8. not planned

Also, when creating a new PID namespace using unshare, the calling process remains in its existing namespaces and only
the children are moved to the new one, unlike other namespaces. This is stated in the man page for unshare. Also see `man
pid_namespaces`.

**Comment by matu3ba** [comment]
That's great to hear.

> I'm not quite sure what you're trying address there.

Point 3 should have been that one can use the `clone` flags to do all the stuff unshare can do as well, so there is no reason to use 2 syscalls (besides the implementation/binding effort).
Point 4 is that signaling via pid is fundamentally racy on the sender side, which is eliminated with a pid_fd as clone flag (CLONE_PIDFD), but this might not be your main focus with zcrun. Context https://lwn.net/Articles/794707/.

Yep, I do understand that implication. My main points was that "must create a child process" is not necessary, exec(ve) with the current process is enough.

**Comment by 1nwf** [comment]
Thanks for clarifying. I agree, using clone instead of unshare & fork would be better. Also, I'm not sure that there would be a race condition in this case since we only wait for the child process to terminate. 

To address your other point, in order to enter the new pid namespace, you must create a child process. execv inherits the current process's pid as well as the pid namespace. Here is a snippet from the nsproxy struct in the linux kernel from `include/linux/nsproxy.h`
```c
/*
 * A structure to contain pointers to all per-process
 * namespaces - fs (mount), uts, network, sysvipc, etc.
 *
 * The pid namespace is an exception -- it's accessed using
 * task_active_pid_ns.  The pid namespace here is the
 * namespace that children will use.
 *
 * 'count' is the number of tasks holding a reference.
 * The count for each namespace, then, will be the number
 * of nsproxies pointing to it, not the number of tasks.
 *
 * The nsproxy is shared by tasks which share all namespaces.
 * As soon as a single namespace is cloned or unshared, the
 * nsproxy is copied.
 */
struct nsproxy {
	refcount_t count;
	struct uts_namespace *uts_ns;
	struct ipc_namespace *ipc_ns;
	struct mnt_namespace *mnt_ns;
	struct pid_namespace *pid_ns_for_children;
	struct net 	     *net_ns;
	struct time_namespace *time_ns;
	struct time_namespace *time_ns_for_children;
	struct cgroup_namespace *cgroup_ns;
};
```
you can see that `pid_ns_for_children` is for child processes. Assuming you just use execv, or similar syscalls,
after creating a new pid namespaces using unshare, you will remain in the caller's pid namespaces until you create a child
process.
